import fs from 'node:fs';
import path from 'node:path';

import { loadCapabilityCatalog } from '../src/capability-manifest.js';

const root = process.cwd();
const outputPath = path.join(root, 'docs', 'generated', 'CAPABILITY-MATRIX.md');

function cell(values: string[]): string {
  return values.length ? values.join(', ') : 'none';
}

function render(): string {
  const manifests = loadCapabilityCatalog(root);
  const rows = manifests.map((manifest) => {
    const mounts = [
      ...manifest.mounts.base.map((name) => `${name}:host-defined`),
      ...manifest.mounts.additional.map(
        (mount) =>
          `${mount.target}:${mount.access === 'read_only' ? 'ro' : 'rw'}`,
      ),
    ];
    const runtime = [
      `models=${manifest.runtime.models.join('/')}`,
      `turn=${manifest.runtime.timeoutMsMax}ms`,
      `spawn=${manifest.runtime.spawnTimeoutMsMax}ms`,
      `idle=${manifest.runtime.idleTimeoutMsMax}ms`,
      `memory=${manifest.runtime.memoryMbMax}MB`,
      `cpus=${manifest.runtime.cpusMax}`,
    ].join('; ');
    return `| ${manifest.agent.folder} | ${manifest.agent.owner} | ${cell(manifest.inputs)} | ${cell(manifest.dataDomains)} | ${cell(manifest.tools.claude)} | ${cell(manifest.tools.mcp)} | ${cell(manifest.tools.hostOperations)} | ${cell(mounts)} | ${manifest.network.mode} | ${cell(manifest.actions.classes)} / ${manifest.actions.approval} | ${runtime} | ${manifest.slo.name}: ${manifest.slo.target} |`;
  });
  return [
    '# Generated Capability Matrix',
    '',
    '> Generated by `npm run capabilities:generate` from tracked manifests in `capabilities/`. Do not edit this file by hand.',
    '>',
    '> Host paths and credentials are deliberately excluded. `unrestricted_current` records the present container egress reality; it is not a claim of network enforcement.',
    '',
    '| Agent | Owner | Inputs | Data domains | Claude tools | MCP tools | Host operations | Mount targets | Network | Action classes / approval | Runtime ceilings | SLO |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

const expected = render();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, 'utf8')
    : '';
  if (current !== expected) {
    process.stderr.write(
      'Capability matrix is stale. Run npm run capabilities:generate.\n',
    );
    process.exitCode = 1;
  }
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, expected);
}
